version: '3.9'
services:
  db:
    container_name: postgresDB
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    networks:
      - bank-network

  sqlc:
    container_name: sqlc
    image: sqlc/sqlc
    volumes:
      - '.:/src'
    working_dir: /src
    command: ['generate']
    depends_on:
      - db
