version: '3.9'
services:
  db:
    container_name: postgresDB
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '9090:9090'
    environment:
      - DB_SOURCE=postgresql://myuser:mypassword@postgresDB:5432/simple_bank?sslmode=disable
    depends_on:
      - db
    entrypoint: ['/app/wait-for.sh', 'postgresDB:5432', '--', '/app/start.sh']
    command: ['/app/main']
  sqlc:
    container_name: sqlc
    image: sqlc/sqlc
    volumes:
      - '.:/src'
    working_dir: /src
    command: ['generate']
    depends_on:
      - db
